// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitterScraper.API;

namespace TwitterScraper.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200226022723_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("TwitterScraper.API.Entidades.Hashtag", b =>
                {
                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.HasKey("Texto");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("TwitterScraper.API.Entidades.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("TwitterScraper.API.Entidades.MensagemHashtag", b =>
                {
                    b.Property<Guid>("MensagemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hashtag")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("MensagemId", "Hashtag");

                    b.ToTable("MensagemHashtag");
                });

            modelBuilder.Entity("TwitterScraper.API.Entidades.MensagemHashtag", b =>
                {
                    b.HasOne("TwitterScraper.API.Entidades.Mensagem", "Mensagem")
                        .WithMany("MensagemHashtags")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
